error[E0599]: no method named `deref_err` found for type `std::result::Result<_, {integer}>` in the current scope
  --> $DIR/result-deref-err.rs:4:28
   |
LL |     let _result = &Err(41).deref_err();
   |                            ^^^^^^^^^
   |
   = note: the method `deref_err` exists but the following trait bounds were not satisfied:
           `{integer} : std::ops::Deref`
   = help: did you mean `deref_ok`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
